learningtemplates/base_app/urls.py
from django.urls import path
from base_app import views
app_name = 'base_app'
urlpatterns = [
    path('', views.index,name="index"),
    path('other/', views.other,name="other"),
    path('relative/', views.relative,name="relative"),
]

learningtemplates/learningtemplates/urls.py
from django.contrib import admin
from django.urls import path, include
from base_app import views

urlpatterns = [
    path('', views.index,name="index"),
    path('base_app/', include('base_app.urls')),
    path('admin/', admin.site.urls),
]

learningtemplates/base_app/models.py
from django.db import models

# Create your models here.

learningtemplates/base_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':"hello world",'number':100}
    return render(request, 'base_app/index.html', context_dict)
def other(request):
    return render(request, 'base_app/other.html')
def relative(request):
    return render(request, 'base_app/relative_url_templates.html')

learningtemplates/base_app/templates/base_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script></head>

</head>
<body>
	<nav class="navbar navbar-default nabar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
					<li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
					<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
					<li><a class="navbar-link" href="{% url 'base_app:other' %}">Other</a></li>

			</ul>
		</div>
	</nav>
	<div class="container">
		{% block body_block %}

		{% endblock %}
	</div>
</body>
</html>

learningtemplates/base_app/templates/base_app/index.html
<!DOCTYPE html>
{%extends "base_app/base.html"%}
{%block body_block%}
	<h1>Welcome to index!</h1>
	<h1>{{text|cut:'hello'}}</h1>
	<h1>{{number|add:"99"}}</h1>
	{% endblock %}

learningtemplates/base_app/templates/base_app/other.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{%block body_block %}
	<h1>Welcome to other!</h1>
{% endblock %}

learningtemplates/base_app/templates/base_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Welcome to relative url templates</h1>
	<a href="{% url 'base_app:other' %}">The other page</a>
</body>
</html>